### ISSUE TITLE
start.bat error when profile directory has spaces

### ISSUE THREAD

**Issue by josueharos** [vitr/valet4windows#10]
C:\Users\Josue Haros\AppData\Roaming\Composer\vendor\vitr\valet4windows>2016/12/
13 16:01:27 args:2 - Parse error: Unknown directive 'Haros\.valet\Caddyfile'

i fixed it by enclosing this line in start.bat
start /b bin/caddy --conf=%HOMEDRIVE%%HOMEPATH%\.valet\Caddyfile
with "
start /b bin/caddy --conf="%HOMEDRIVE%%HOMEPATH%\.valet\Caddyfile"

**Comment by vitr** [comment]
@josueharos thanks for the fix, really appreciate your help!
just released that https://packagist.org/packages/vitr/valet4windows
