### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by victormongi** [vitr/valet4windows#11]
![image](https://cloud.githubusercontent.com/assets/5617746/23196713/5d81279a-f8f6-11e6-9640-2ac1a219c339.png)

![image](https://cloud.githubusercontent.com/assets/5617746/23196667/0994be58-f8f6-11e6-9a22-4b5cf1eceaf7.png)
Help me ive got this error...

**Comment by victormongi** [comment]
After I upgrade to PHP 7.1 ive got this error
![image](https://cloud.githubusercontent.com/assets/5617746/23245672/4867172e-f9c9-11e6-90ef-c76a7c090360.png)

**Comment by victormongi** [comment]
Problem Resolve, sorry my bad...
I have to clear my composer cache and reinstall the vitr/valet4windows...
Thank you this tool are great...

**Comment by vitr** [comment]
hey @victormongi , np, glad you like it ;)
