### ISSUE TITLE
valet start cannot find .bat

### ISSUE THREAD

**Issue by mbouclas** [vitr/valet4windows#2]
when doing valet start i get a prompt :
Windows cannot find .bat. Make sure you typed the name correctly, and then try again

Win 10 both on cmd and cygwin.
Valet scan worked fine though as did the install command

**Comment by vitr** [comment]
have got this folder?
`c:\Users\YourUserName\AppData\Roaming\Composer\vendor\vitr\valet4windows\`

**Comment by mbouclas** [comment]
it's looking for start.bat but can't find it in VALET_BIN_PATH.'/../ && start.bat" The file is indeed in
C:\Users\mbouc\AppData\Roaming\Composer\vendor\vitr\valet4windows

**Comment by vitr** [comment]
well, that's correct, keep in mind cmd doesn't work at all.
may I ask you to try back slashes?
`.VALET_BIN_PATH.'\..\ && start.bat"'`
I never tested on cygwin, I use git-bash all the way

**Comment by mbouclas** [comment]
ok, git-bash works better, but then i get 
2016/08/01 16:51:26 open \Users\us\.valet\Caddyfile: The system cannot find the path specified

**Comment by vitr** [comment]
sorry, why is that `us.valet`? I've got just `.valet` in my home dir

**Comment by mbouclas** [comment]
sorry, it's us\valet (replaced my username)

**Comment by vitr** [comment]
it must be with the dot, it creates the folder on install
```
/**
 * Define the ~/.valet path as a constant.
 */
define('VALET_HOME_PATH', $_SERVER['HOMEPATH'].'/.valet');
```

**Comment by vitr** [comment]
`valet park` should create `config.json`, it's a crucial file for the app.
I'd appreciate, if you can debut the park command, when it creates files, does it work at all?

**Comment by mbouclas** [comment]
so, valet park does not create a folder .valet or a config.json
echo VALET_HOME_PATH.'/config.json'; in your path method returns the right path.

To sum up, 
when running 
``` 
valet install
valet park
```
from a clean installation, the .valet folder is not created and of course this causes the config.json to not be created. 
If you manually create a .valet folder and run the above commands, you still don't get anything in the .valet folder.

The write method does get the path correctly, the contents of the config file to write are
```
{
    "domain": "dev",
    "paths": [
        "D:\\Work\\testing\\valet"
    ]
}
```

but the file is not written and no exception is thrown.

Next step was to manually create the config.json in the .valet folder which then leads to 
```
Warning: require(D:\Work\testing\valet\valet\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in D:\Work\testing\valet\valet\bootstrap\autoload.php on line 17
```

**Comment by mbouclas** [comment]
edit, ignore the require, it is a laravel thing. The previous comments stand

**Comment by vitr** [comment]
ok, `valet install` does the creation of `~/.valet` (in your home dir), If you don't have it, then something goes wrong. Could you run `git-bash` as administrator and try `valet install`? Thank you for your patience and sorry for the troubles.

**Comment by mbouclas** [comment]
So, the run as admin did solve the valet install issue. I got the files written in the .valet directory properly. valet start still throws the cannot find the start.bat file. Starting the start.bat manually (no biggie) and then doing a valet open, it throws a 404

**Comment by vitr** [comment]
can you run `where valet` and post the output?
what's the url of that 404?  if you park testing dir `D:\Work\testing` and scan it, I expect something like
http://valet.dev

**Comment by mbouclas** [comment]
yes, that's the url

**Comment by vitr** [comment]
... and `where valet`? what's inside the `D:\Work\testing\valet` folder? in my how-to it's supposed to be a laravel app (aka blog), valet runs app, but it's not an app itself.

**Comment by mbouclas** [comment]
it's a laravel installation created with laravel new command

**Comment by vitr** [comment]
just run `where valet` and post the outhput here, to confirm that it's in same home folder as the `start.bat`

**Comment by mbouclas** [comment]
C:\Users\us\AppData\Roaming\Composer\vendor\bin\valet
C:\Users\us\AppData\Roaming\Composer\vendor\bin\valet.bat

and they are 100% correct

**Comment by vitr** [comment]
gotcha! just reproduced this.
as a quick fix, you can run `cd  /C/Users/us`  and run `valet start` from there, should work.
Meanwhile, I'm trying to understand the issue with d: drive, I guess, it's windows bash thing, sorry, I never run it outside of my users dir))

**Comment by mbouclas** [comment]
true, when valet start in the home folder, it starts fine. Still getting the 404 though. Is there a way to debug the output, to see what it's trying to open?

**Comment by vitr** [comment]
try `valet logs`, but I doubt this, I guess, it's working only if everything is in your home dir((

**Comment by vitr** [comment]
OK, I just missed `$_SERVER['HOMEDRIVE']`  in the valet path)), please, pull the code from the repo, and try again, see https://github.com/vitr/valet4windows/commit/25a65d28ff52644781ad7956383af44d82ff5721

**Comment by vitr** [comment]
closing this, feel free to comment, if it's not resolved for you
