### ISSUE TITLE
Valet Fatal error

### ISSUE THREAD

**Issue by rafix** [vitr/valet4windows#5]
When I try to run the valet command I got this error:

Fatal error: Cannot declare class Brew, because the name is already in use in C:\Users\rafix\AppData\Roaming\Composer\vendor\vitr\valet4windows\cli\includes\facades.php on line 28

**Comment by vitr** [comment]
we don't actually need brew (it's a mac leftover), but what command are you trying to run?
just `valet`? did you run `valet install` initially?

**Comment by vitr** [comment]
can't reproduce, please, feel free to reopen with  more details
